FROM UPSTREAM_REPO

RUN { \
      echo 'client_max_body_size 100m;'; \
    } > /etc/nginx/conf.d/drud.conf

RUN 	apt-get -qq update && \
    	apt-get -qq install --no-install-recommends --no-install-suggests -y vim less telnet

ADD . /app/

