# jwilder/nginx-proxy does not have a recent tagged image, so one was created
# in our namespace by checking out jwilder/nginx-proxy master @ commit 0c03c90
FROM drud/nginx-proxy:0c03c90

ENV DEBIAN_FRONTEND noninteractive

RUN { \
      echo 'client_max_body_size 100m;'; \
    } > /etc/nginx/conf.d/ddev.conf

RUN   apt-get -qq update && \
      apt-get -qq install --no-install-recommends --no-install-suggests -y vim less telnet curl && \
      apt-get autoremove -y && \
      apt-get clean -y && \
	rm -rf /var/lib/apt/lists/*

ADD . /app/

HEALTHCHECK --interval=5s --retries=5 CMD curl --fail http://localhost/healthcheck || exit 1
